# Minha Página

> Aprendendo a criar uma página de blog com Jupyter Notebook

- toc: false
- branch: master
- badges: false
- comments: false
- author: Diego Leal
- categories: [blog]

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.randint(0,1000, (10,10))
data

array([[998, 242, 782, 416, 301, 115, 344, 531, 124, 731],
       [312, 671, 899, 283, 661, 589, 461, 424, 691, 878],
       [450, 679, 384, 932, 646, 905, 670, 561, 495, 361],
       [466,  29, 721, 684, 762, 990, 631, 357, 371, 930],
       [870, 288, 876, 190,  65, 866, 859, 678, 218, 176],
       [329, 301, 751,  20, 844, 423, 511, 831, 440, 597],
       [347, 788, 658, 820, 739, 364, 774, 644, 232, 721],
       [983, 190, 450,  86, 174, 523,   0, 327, 321, 804],
       [786, 951,  95, 706, 576, 187, 381,  12, 462, 726],
       [479, 328, 718, 313, 478, 311, 795, 980, 881, 710]])

In [3]:
df1 = pd.DataFrame(data)
df1

     0    1    2    3    4    5    6    7    8    9
0  998  242  782  416  301  115  344  531  124  731
1  312  671  899  283  661  589  461  424  691  878
2  450  679  384  932  646  905  670  561  495  361
3  466   29  721  684  762  990  631  357  371  930
4  870  288  876  190   65  866  859  678  218  176
5  329  301  751   20  844  423  511  831  440  597
6  347  788  658  820  739  364  774  644  232  721
7  983  190  450   86  174  523    0  327  321  804
8  786  951   95  706  576  187  381   12  462  726
9  479  328  718  313  478  311  795  980  881  710

In [6]:
#hide_input
df2 = pd.DataFrame(data)
df2

     0    1    2    3    4    5    6    7    8    9
0  998  242  782  416  301  115  344  531  124  731
1  312  671  899  283  661  589  461  424  691  878
2  450  679  384  932  646  905  670  561  495  361
3  466   29  721  684  762  990  631  357  371  930
4  870  288  876  190   65  866  859  678  218  176
5  329  301  751   20  844  423  511  831  440  597
6  347  788  658  820  739  364  774  644  232  721
7  983  190  450   86  174  523    0  327  321  804
8  786  951   95  706  576  187  381   12  462  726
9  479  328  718  313  478  311  795  980  881  710

In [7]:
#hide
df3 = pd.DataFrame(data)
df3

     0    1    2    3    4    5    6    7    8    9
0  998  242  782  416  301  115  344  531  124  731
1  312  671  899  283  661  589  461  424  691  878
2  450  679  384  932  646  905  670  561  495  361
3  466   29  721  684  762  990  631  357  371  930
4  870  288  876  190   65  866  859  678  218  176
5  329  301  751   20  844  423  511  831  440  597
6  347  788  658  820  739  364  774  644  232  721
7  983  190  450   86  174  523    0  327  321  804
8  786  951   95  706  576  187  381   12  462  726
9  479  328  718  313  478  311  795  980  881  710